{% set name = "limits" %}
{% set version = "5.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c9e0d74aed837e8f6f50d1fcebcf5fd8130957287206bc3799adaee5092655da

build:
  number: 0
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    - deprecated >=1.2
    - packaging >=21,<25
    - typing_extensions

test:
  imports:
    - limits
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/alisaifee/limits
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Rate limiting utilities
  description: Rate limiting using various strategies and storage backends such as redis, memcached & mongodb
  doc_url: https://limits.readthedocs.io/en/stable/
  dev_url: https://github.com/alisaifee/limits

extra:
  recipe-maintainers:
    - tiefling-cat
