{% set name = "limits" %}
{% set version = "2.2.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: da6346f0dcf85f17f0f1cc709c3408a3058cf6fee68313c288127c287237b411

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install --no-deps --no-build-isolation . -vv"

requirements:
  host:
    - pip
    - python >=3.7
    - wheel
  run:
    - python >=3.7
    - setuptools

test:
  requires:
    - pip
  imports:
    - limits
  commands:
    - pip check

about:
  home: https://github.com/alisaifee/limits
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: "Rate limiting utilities"
  doc_url: https://limits.readthedocs.io/en/stable/
  dev_url: https://github.com/alisaifee/limits

extra:
  anaconda-services:
    ref: https://anaconda.zendesk.com/agent/tickets/43927
    reason: Dependency for slowapi package
  recipe-maintainers:
    - ianaobi
    - tiefling-cat
